server:
  type: default
  rootPath: /api/*
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  loggers:
    com.example: DEBUG
    org.eclipse.jetty: DEBUG
    org.eclipse.jetty.websocket: DEBUG

websocket:
  maxTextMessageSize: 65536
  idleTimeout: 600000